# Generated by Django 5.1.7 on 2025-03-26 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Project name')),
                ('description', models.TextField(verbose_name='Description')),
                ('image', models.ImageField(blank=True, default='projects_images/default_project_image.png', null=True, upload_to='projects_images/', verbose_name='Project image')),
                ('tools', models.CharField(max_length=255, verbose_name='Tools (comma separated)')),
                ('category', models.CharField(choices=[('game', 'Game'), ('app', 'Application'), ('coming', 'Coming Soon')], default='coming', max_length=20, verbose_name='Category')),
            ],
        ),
    ]
